name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Virtual Display
        uses: pyvista/setup-headless-display-action@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependency
        run: pip install tox

      - name: Test
        run: python -m tox run -e test

      - name: Check Format
        run: python -m tox run -e check_format
